"""Gate the generated social share pages + the journalist embed kit.

The /s/<id> pages and /embed-kit are generated by etl.build_share_pages from
stories.json (their OG descriptions ARE the computed finding, never hand-typed).
build.py regenerates them on every build. This test asserts the committed files
exist, carry the right per-story Open Graph meta, point at an OG card image that
exists, and have NOT drifted from what the generator produces now — so a
stories.json change without a regen fails CI, the same way the manifest drift
guard works.
"""

from __future__ import annotations

import json
import re
import subprocess
import tempfile
from pathlib import Path

from etl.build_share_pages import write_share_pages

PUBLIC = Path(__file__).resolve().parent.parent / "public"
STORIES = json.loads((PUBLIC / "data" / "stories.json").read_text())


def test_every_preset_has_a_share_page() -> None:
    for s in STORIES:
        sid = s["id"]
        page = PUBLIC / "s" / sid / "index.html"
        assert page.exists(), f"missing share page public/s/{sid}/index.html"
        html = page.read_text()
        assert f"/og/{sid}.png" in html, f"{sid} share page does not reference its OG card"
        assert f"url=/#story={sid}" in html, f"{sid} share page does not redirect to the chart"
        assert 'property="og:title"' in html and 'name="twitter:card"' in html, (
            f"{sid} share page missing OG/Twitter meta"
        )


def test_share_page_og_description_is_the_computed_finding() -> None:
    """og:description must be the finding's first claim, not hand-written copy."""
    for s in STORIES:
        finding = s.get("finding") or {}
        sentence = finding.get("sentence")
        if not sentence:
            continue
        html = (PUBLIC / "s" / s["id"] / "index.html").read_text()
        m = re.search(r'property="og:description" content="([^"]*)"', html)
        assert m, f"{s['id']}: no og:description"
        desc = m.group(1).replace("&amp;", "&").replace("&quot;", '"').replace("&#x27;", "'")
        # The first computed claim (up to the first sentence end) must be present.
        first_claim = sentence.split(". ", 1)[0]
        assert first_claim[:60] in desc, (
            f"{s['id']}: og:description is not the computed finding ({desc!r})"
        )


def test_every_story_has_an_og_card_image() -> None:
    for s in STORIES:
        img = PUBLIC / "og" / f"{s['id']}.png"
        assert img.exists(), (
            f"missing OG card public/og/{s['id']}.png (run node docs/build_og_cards.js)"
        )
        assert img.stat().st_size > 5000, f"OG card {s['id']}.png is suspiciously small"


def test_og_card_axis_labels_come_from_indicator_metadata() -> None:
    """Cards must describe the selected indicators, not a hard-coded poverty plot."""
    script = PUBLIC.parent / "docs" / "build_og_cards.js"
    probe = """
const cards = require(process.argv[1]);
console.log(JSON.stringify({
  poverty: cards.axisLabel('poverty'),
  gdp: cards.axisLabel('gdp_per_capita'),
  spend: cards.axisLabel('all_spend_per_capita'),
}));
"""
    result = subprocess.run(
        ["node", "-e", probe, str(script)],
        check=True,
        capture_output=True,
        text=True,
    )
    labels = json.loads(result.stdout)
    assert labels == {
        "poverty": "Poverty incidence among families",
        "gdp": "Per capita GDP",
        "spend": "All PhilGEPS spend per capita",
    }


def test_embed_kit_has_a_snippet_per_preset() -> None:
    kit = PUBLIC / "embed-kit" / "index.html"
    assert kit.exists(), "missing public/embed-kit/index.html"
    html = kit.read_text()
    for s in STORIES:
        assert f"story={s['id']}&amp;embed=1" in html, f"embed kit missing snippet for {s['id']}"
    assert html.count('class="copy"') == len(STORIES), "one copy button per preset expected"
    assert (PUBLIC / "embed-kit.js").exists(), "missing public/embed-kit.js"
    assert "The embed keeps the active view state" in html


def test_share_pages_match_generator() -> None:
    """Drift guard: regenerating from stories.json must reproduce the committed
    files byte-for-byte. If this fails, run `python -m etl.build_share_pages`."""
    with tempfile.TemporaryDirectory() as td:
        tmp = Path(td)
        written = write_share_pages(STORIES, tmp)
        for rel in written:
            generated = (tmp / rel).read_text()
            committed = (PUBLIC / rel).read_text()
            assert generated == committed, (
                f"public/{rel} drifted from etl.build_share_pages; "
                f"run `python -m etl.build_share_pages`"
            )
